#!/usr/bin/env bash
# write a bash script that configures a new ubuntu machine

sudo apt-get update

apt install -y nginx

echo "Hello world!" > /var/www/html/index.html

sudo ufw allow 'Nginx HTTP'

service nginx restart
