#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get update
sudo apt-get install -y nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'

sudo sed -i "/location \/ {/a \\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx restart
