#!/usr/bin/bash
# the code for that

docker exec -it <container_id> /bin/bash

cd /etc/apache2/sites-available

nano 000-default.conf

<VirtualHost *:80>
    DocumentRoot /var/www/html
    # ... other configurations ...
</VirtualHost>

service apache2 restart

exit

curl 0:8080

