#!/bin/bash
# Your Bash script must be 7 lines long or less
sed -i 's/user\s*nginx/user nginx/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80/listen 8080/' /etc/nginx/conf.d/default.conf
systemctl restart nginx

