#!/bin/bash
# Your Bash script must be 7 lines long or less
sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80 /8080 /g" /etc/nginx/sites-available/default
pkill -9 apache
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start

